### PR TITLE
Call XAck inside Delete in redsiq

### LINKED ISSUE #143: redisq isn't acknowledging processed messages.
Please correct me If I'm wrong. I have been running a script to generate events and consumer likewise with the code below:

```
// Define Our Queues
 var (
	ScheduledQueue = QueueFactory.RegisterQueue(&taskq.QueueOptions{
		Name:  "ScheduledQueue",
		Redis: redisClient,
	})
 )

// Define Task
 var (
	WorkProcessor = taskq.RegisterTask(&taskq.TaskOptions{
		Name:       "WorkProcessor",
		RetryLimit: 10,
		Handler: func(job *Job) error {
			log.Printf("Processing Job - %s", job.ID)
			
			return nil
		},
	})
 )

// Schedule task.
 err := ScheduledQueue.Add(msg)
 if err != nil {
	log.Printf("Error occurred scheduling job - %s", job.ID)
 }
```

When I check the logs after the `ReservationTimeout` is past, I start to multiple lines of see:

```
taskq: 2021/10/12 13:27:24 queue.go:296: redisq: pending failed: redisq: can't find peding message id="1634040420749-0" in stream="taskq:{ScheduledQueue}:stream"
```

Then I go into `redis-cli` and perform `xack taskq:{ScheduledQueue}:stream taskq 1634040419532-1` and the entry is acknowledged and it starts to complain about the next item in the Pending List.

Am I doing something wrong or is this a bug? 

Thanks

### PR DESCRIPTION
**Pull request by subomi**
Fixes #143

### CODE REVIEW

**Comment by vmihailenco** [comment]
Is it possible to write a test that demonstrates the problem and that fails without this change? We have some tests in https://github.com/vmihailenco/taskq/blob/v3/redisq_test.go, but it looks like that is not enough...

**Comment by subomi** [comment]
@vmihailenco I'd give it a shot.

**Comment by subomi** [comment]
@vmihailenco I added a test to expose the bug. Essentially, I am using the log lines to detect the failure. It seems quite tacky, but this was the sanest way I found to do it. 

Other methods will require us to either query redis directly or expose a new interface that gives us the pending count. 

Let me know what you think.

**Comment by vmihailenco** [comment]
@Subomi thanks :+1:  If that is not too much trouble, could you instead query redis directly to check if there any pending messages? I It  looks like that is what we are essentially trying to test and I think it is fine to write a redis specific test here...

**Comment by subomi** [comment]
Hmm. @vmihailenco by redis specific test is there any example in the code I can follow?

**Comment by vmihailenco** [comment]
@Subomi I just mean that this test won't work for SQS and that is fine. I suggest to add something like

```
	pending, err := rdb.XPendingExt(ctx, &redis.XPendingExtArgs{
		Stream: q.stream,
		Group:  q.streamGroup,
		Start:  "-",
		End:    end,
		Count:  batchSize,
	}).Result()
```

And check that there no pending messages when all tasks are processed.

**Comment by subomi** [comment]
Alright. @vmihailenco I'll work on it. Thanks

**Comment by subomi** [comment]
@vmihailenco Done. :)

**Comment by vmihailenco** [comment]
Thanks :+1:

**Pull request merged**
