### PR TITLE
Bump aws-sdk-go to v1.40.25

### PR DESCRIPTION
**Pull request by lilien1010**

### CODE REVIEW

**Comment by lilien1010** [comment]
@vmihailenco  does the CI being removed?

**Comment by vmihailenco** [comment]
@lilien1010 we used Travis and it is no longer working. Github actions look like a better alternative now.

I don't actively use taskq/SQS any more, because I need to be able to process messages in batches which is not possible/easy with SQS. So I am using Kafka which is way too different to add it to taskq...

I will send you an invite in case you are interested in maintaining taskq.

**Comment by lilien1010** [comment]
hi @vmihailenco ,  I am using this project in our production project, and would like to help to make this project better.

**Comment by lilien1010** [comment]
TBH, I am also using Redis queue only

**Pull request merged**
